language: node_js
node_js:
  - 6
  - node
env:
  - NODE_ENV=production
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm --production=false install
  - npm --production=false update
  - npm --production=false prune
